# Fly.io configuration for NobelLM Frontend
app = "nobellm-web"

[build]
  dockerfile = "Dockerfile"

[env]
  VITE_API_URL = "https://nobellm-api.fly.dev"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512 