# Fly.io configuration for NobelLM Backend API
app = "nobellm-api"

[build]
  dockerfile = "backend/Dockerfile"

[env]
  TOKENIZERS_PARALLELISM = "false"
  ENVIRONMENT = "production"
  NOBELLM_ENVIRONMENT = "production"
  ALLOWED_ORIGINS = '["https://nobellm.com", "https://www.nobellm.com"]' 

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[http_service.health_check]
path = "/health"
interval = "15s"
timeout = "10s"
grace_period = "60s"
method = "get"


[[vm]]
  cpu_kind = "performance"
  cpus = 1
  memory_mb = 2048
