name: Sync to Hugging Face Space

on:
  push:
    branches: [main]

jobs:
  sync-space:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with LFS
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action Bot"

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote remove space || true
          git remote add space https://huggingface.co/spaces/yogonwa/NobelLM-RAG
          git push space main --force
