[server]
headless = true
port = 8501
maxUploadSize = 200
maxMessageSize = 200
fileWatcherType = "none"
enableCORS = false
enableXsrfProtection = false

[client]
showErrorDetails = true

[theme]
base = "light"
primaryColor = "#3366cc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[browser]
gatherUsageStats = false
